name: 👷 CI

on:
  push:
    branches:
      - master
      - ci

  pull_request:
    branches:
      - master

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: ['Release', 'Debug']

    steps:
      -
        uses: actions/checkout@v2
      -
        name: 🔧 Configure Endn
        run: |
          cmake -E make_directory build
          cmake -DENDN_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -B build -S .
        shell: bash
      -
        name: 🔨 Build Tests
        run: |
          cmake --build build --target "EndnTests" --config "${{ matrix.build_type }}" -j
      -
        name: ✅ Run Tests
        run: cd build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose
